export enum combinations {
    ScissorsPaper = "ScissorsPaper",
    RockScissors = "RockScissors",
    PaperRock = "PaperRock",
    LizardPaper = "LizardPaper",
    SmockScissors = "SmockScissors",
    RockLizard = "RockLizard",
    PaperSmock = "PaperSmock",
    SmockRock = "SmockRock",
    ScissorsLizard = "ScissorsLizard",
    LizardSmock = "LizardSmock",
    RockRock = "RockRock",
    PaperPaper = "PaperPaper",
    ScissorsScissors = "ScissorsScissors",
    LizardLizard = "LizardLizard",
    SmockSmock = "SmockSmock",
  }