export enum Combinations {
  ScissorsPaper = "ScissorsPaper",
  RockScissors = "RockScissors",
  PaperRock = "PaperRock",
  LizardPaper = "LizardPaper",
  SpockScissors = "SpockScissors",
  RockLizard = "RockLizard",
  PaperSpock = "PaperSpock",
  SpockRock = "SpockRock",
  ScissorsLizard = "ScissorsLizard",
  LizardSpock = "LizardSpock",
  RockRock = "RockRock",
  PaperPaper = "PaperPaper",
  ScissorsScissors = "ScissorsScissors",
  LizardLizard = "LizardLizard",
  SpockSpock = "SpockSpock",
  PaperScissors = "PaperScissors",
  ScissorsRock = "ScissorsRock",
  RockPaper = "RockPaper",
  PaperLizard = "PaperLizard",
  ScissorsSpock = "ScissorsSpock",
  LizardRock = "LizardRock",
  SpockPaper = "SpockPaper",
  RockSpock = "RockSpock",
  LizardScissors = "LizardScissors",
  SpockLizard = "SpockLizard",
}
